### ISSUE TITLE
How to prevent macro detection

### ISSUE THREAD

**Issue by RedScorpX** [machacks02/dankMemerHack#2]
the code is good but it will surely be detected if you don't use random waiting numbers
instead of using for example ' time.sleep(45.5) ' use ' time,sleep(numpy.random.randint(45.5, 47.5)) '
this will give the timer a random number between 45.5 to 47.5, this way they can not detect you
remember, bots are detected since they use specific numbers, humans are random
![{44F06BD2-F541-49ED-8340-387CA4ABA6F2}](https://user-images.githubusercontent.com/38502084/119252192-892e8700-bbb3-11eb-9c99-ee3d05b1c99d.png)

**Comment by machacks02** [comment]
I fixed this, thanks for the advice!
