### ISSUE TITLE
Grammer issue - pls search outdated

### ISSUE THREAD

**Issue by FeelsBadMan1** [machacks02/dankMemerHack#6]
Hey, i just found a little typingissue in the readme.md probably you should fix it or some randoms try to install it lmao

**pyauogui** Pillow

![image](https://user-images.githubusercontent.com/40109798/131664136-ef57e7a5-5469-4aed-8e69-58d14346bfc7.png)

Also pls seach command is outdated a bit. now the options you can choose are made with buttons below the embedmessage so you would need to somehow press the button:
![image](https://user-images.githubusercontent.com/40109798/131665449-6475a930-e0a4-4be5-a319-25da5b5119e5.png)
If the buttons appear it only wrap the textinput around with a blue corner and do nothing else

**Comment by machacks02** [comment]
The code is updated to click the buttons, if this functionality is not working it is likely because an antivirus is blocking it. I'll fix the typo right away.
